### PR TITLE
Use the same request method in the handler and endpoint files

### PR DESCRIPTION
**Pull request by barchard**
Use the same request methodology in both the `UploadHandler` class and
endpoint files. The method is now a static function on the
`UploadHandler` class to allow both functions a clean way for code
re-use.

### CODE REVIEW

**Comment by rnicholus** [comment]
It probably makes sense to include the same changes in endpoint-cors.php.

**Comment by barchard** [comment]
Done

**Comment by rnicholus** [comment]
Are you seeing success with these changes locally? For some reason, DELETE requests work, but POST requests that attempt to delete a file don't actually remove the file from the system.

**Comment by barchard** [comment]
Do you have a test built that I can run locally? The biggest change in all of these patches is how the request method is determined. Did `get_request_method` come from somewhere?

**Comment by rnicholus** [comment]
Upon closer inspection - this pull request should be scrapped as far as I can tell. There is logic in the `handleDelete` method that determines the UUID of the file based on the request method. By hiding the underlying method (DELETE vs POST), we're breaking delete file requests when they are sent via POST. v1.2.1 of this server is correct.

**Comment by barchard** [comment]
I guess I'm missing something, but I don't see how this hides the request method? I don't see how this is largely different than the original patch I submitted [here](https://github.com/barchard/php-traditional-server/commit/874df51538626121017e11d87598496e090950fc). Please educate me :)

Also, I think `$_POST["_method"] != null` should just be `!empty($_POST["_method"])`?

```
public static function get_request_method() {
        global $HTTP_RAW_POST_DATA;
        if(isset($HTTP_RAW_POST_DATA)) {
            parse_str($HTTP_RAW_POST_DATA, $_POST);
        }
        if (isset($_POST["_method"]) && $_POST["_method"] != null) {
            return $_POST["_method"];
        }
        return $_SERVER["REQUEST_METHOD"];
    }
```

**Comment by rnicholus** [comment]
When `$method` is set to the result of that function, and then `$method` is checked when processing the delete file request, we lose sight of the underlying request method (if POST was used).

**Comment by barchard** [comment]
`$method` is only used here:

```
$method = $_SERVER["REQUEST_METHOD"];
if ($method == "DELETE") {        
} else if ($method == "POST") {
} else {
}
```

Does this method not return `"DELETE"` or `"POST"`?

**Comment by rnicholus** [comment]
Starting here: https://github.com/FineUploader/php-traditional-server/pull/15/files#diff-e354cf92d749c9adff9f282fdf93c192R248...

At this point, `$method` will _always_ be "DELETE". So the conditional that takes a different path if the underlying request is "POST" will never be executed.

**Comment by barchard** [comment]
Ah, gotcha. I see it now. Thanks. Let me update the PR to fix that. I think it's still valid for the remaining uses? (I've updated the PR)

**Pull request closed without merging**
