### PR TITLE
Added parameter $name to the combineChunks() method

### PR DESCRIPTION
**Pull request by itantik**
It allows to overwrite the name of the chunked file on the server-side. Similarly to the handleUpload() method.

### CODE REVIEW

**Comment by rnicholus** [comment]
It looks like nothing is passing this parameter though. How will anyone make use of this?

**Comment by itantik** [comment]
It will allow to sanitize the file name or make another customizations before storing:

```php
$uploader = new \UploadHandler();
// ...
// sanitize string:
$name = \Nette\Utils\Strings::webalize($uploader->getName(), '.');
// ...
// in case of chunk/file uploading:
$result = $uploader->handleUpload($uploadDirectory, $name);
// or in case of finalization of concurrent chunk uploading:
$result = $uploader->combineChunks($uploadDirectory, $name);
// ...
```

Method handleUpload() provides this option, but combineChunks() does not.

**Comment by rnicholus** [comment]
I see. this requires to user/integrator update the source on their end?

**Comment by itantik** [comment]
Nothing will change in the current endpoint code. Parameter `$name` in the `combineChunks($uploadDirectory, $name = null)` is optional, as well as in the` handleUpload($uploadDirectory, $name = null)`.

New is that now it will be possible to change the file name through endpoint handler. Eg. submit the file `"Bilder für Bücher.JPG"`, rename it and store as `"bilder-fur-bucher.jpg"`.

Current version of `UploadHandler` class allows it through method `handleUpload($uploadDirectory, $name = null)`, but the second parameter is missing in `combineChunks($uploadDirectory)`.

**Comment by rnicholus** [comment]
Alrighty. Thanks for the PR. I'll merge this in and re-tag the repo.

**Comment by itantik** [comment]
Great! Thank you very much.

**Pull request merged**
