### PR TITLE
Fixed issue with non-well formed number notice

### PR DESCRIPTION
**Pull request by akumaburn**
If PHP notices are on, toBytes($str) will throw a notice that $val is a non-well formed number, and this will be pre-pended to the JSON response causing an error in the parser.

Fixed by turning $val into well formed number.

### CODE REVIEW

**Comment by rnicholus** [comment]
This doesn't look correct. Why are you ignoring the last character in `$str`? Seems like that will turn `"123"` into `12`.

**Comment by akumaburn** [comment]
Fixed issue in 0808586.

**Comment by rnicholus** [comment]
Still not sure this is correct, or necessary. Why not just omit the length param?

**Comment by akumaburn** [comment]
What length param? 
This function turns strings like
24G or 1200M or 520K into their byte equivalents

Not sure what you mean by length param?

**Comment by rnicholus** [comment]
`substr(string, start, length)`

**Comment by akumaburn** [comment]
That would not work? If you omit length param with start of 0, you get the whole string, we want to trim last character if it is a letter, so we don't end up multiplying letters which throws the notice.

**Comment by akumaburn** [comment]
```
$str = "abcdef";
echo substr($str, 0);

```
Results in:

`abcdef`

**Comment by rnicholus** [comment]
how is all of this related to "PHP notices"?

**Comment by rnicholus** [comment]
...and is "abcdef" an expected input for this method? If so, omitting the last character doesn't fix the issue either.

**Comment by akumaburn** [comment]
If you have a string like

"1000G", and you try to multiply it by say 10,
ie:
$str = "1000G";
$val = $str * 10;

PHP will throw a "non well formed numeric value" notice, because $str has a letter in it.

No, expected input is:

INTEGER concat 1 letter

letter is optional

**Comment by rnicholus** [comment]
In that case, why not just replace all of this with `$val = (int) trim($str);`. It seems to have the same effect and doesn't assume there is only one trailing character, plus you eliminate the entire conditional.

**Comment by akumaburn** [comment]
Because casting a string, say "1000G" to "1000" is well defined.
"1000G" is not a number, it is an alphanumeric string, should not be casted to an int to begin with.

**Comment by rnicholus** [comment]
Makes sense. But what is `$str` is neither a number nor a string? What if it is a boolean? This is possible, since the value is provided by `ini_get`, which returns `false` if the config option has not been set.

**Comment by akumaburn** [comment]
True, but for file upload script, it is presumed to be set? also it is set by default in php.ini https://github.com/php/php-src/blob/master/php.ini-production

**Comment by rnicholus** [comment]
Gonna have to claim ignorance on this one, since I don't use PHP in any production apps ATM: does that php.ini file always provide default values?

**Comment by akumaburn** [comment]
Yes, I've never seen it empty in production PHP environment, PHP-FPM as well as PHP both provide one, it also comes with LAMP/LEMP stacks like XAMPP or WPN-XM.

**Comment by rnicholus** [comment]
alrighty. thanks for sticking with this. I'm trying to be extra picky about changes to the PHP code because it's so widely used _and_ has 0% automated test coverage. Since I don't use PHP in prod, I haven't been motivated to write tests for this, but I'm hoping someone else will at some point.

**Comment by akumaburn** [comment]
Probably should do trim first before everything also.

**Comment by rnicholus** [comment]
Fix merged and released as [v1.2.2](https://github.com/FineUploader/php-traditional-server/releases/tag/1.2.2). Thanks for your work on this.

**Pull request merged**
