### PR TITLE
Return JSON response result after combining chunks

### PR DESCRIPTION
**Pull request by afelicioni**

### CODE REVIEW

**Comment by rnicholus** [comment]
Can you explain what this is and why it was only applied to the CORS example?

**Comment by afelicioni** [comment]
Using a modified CORS example in a fineuploader server setup.

I was missing the success status and filename returned after _combineChunks_, when files uploaded in chunks. This edit solved a need of mine, maybe a shared scenario.

**Comment by rnicholus** [comment]
>I was missing the success status and filename returned after combineChunks

I don't understand the need for this. Your `onComplete` callback is invoked once the file is finished uploading and all chunks are combined. You have access to the filename via the API at any time client-side. If combineChunks fails, the upload fails and you will be able to determine this in your `onComplete` callback. All that is expected is a status code from this endpoint.

Also, I've found that 99% of the time, the CORS server is used unnecessarily due to a misunderstanding of CORS. Just to be sure, are you certain your upload requests are cross-origin?

**Comment by afelicioni** [comment]
It wasn't clear to me about status inside `onComplete` when an upload in chunks fails, so the patch is unnecessary indeed.

Used the CORS apporach since upload endpoint is from a different domain than the client, acting as a remote file repository.

Thank you

**Comment by rnicholus** [comment]
Glad I could help clear this up. I'll close as a result.

**Pull request closed without merging**
